GET http://localhost:8083/solde/8

PUT http://localhost:8080/employes/7 HTTP/1.1
content-type: application/json

{
  "nom" : "Smith"
}

//POST http://localhost:8080/employes/ HTTP/1.1
//content-type: application/json

//{ 
    //"nom": "Dupond",
    //"prenom": "Charles",
    //"mail": "dupond.charles@beskar.com",
//"password": "ytreza",
    //"adresse": "223 rue du truc",
    //"codepostal": "69003",
   // "ville": "Annecy",
  //  "nsiret": "12052045"
//}

